"""add business_document_url to employer

Revision ID: 0005a4b32ef6
Revises: 4e7a1e273515
Create Date: 2026-06-26 20:16:33.715537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0005a4b32ef6'
down_revision: Union[str, Sequence[str], None] = '4e7a1e273515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('business_document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'business_document_url')
    # ### end Alembic commands ###
