"""add supabase_auth_id

Revision ID: 400d7c5d060b
Revises: 0005a4b32ef6
Create Date: 2026-06-27 12:16:52.816577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '400d7c5d060b'
down_revision: Union[str, Sequence[str], None] = '0005a4b32ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('supabase_auth_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('employers_email_key'), 'employers', type_='unique')
    op.create_index(op.f('ix_employers_email'), 'employers', ['email'], unique=True)
    op.create_index(op.f('ix_employers_supabase_auth_id'), 'employers', ['supabase_auth_id'], unique=True)
    op.add_column('workers', sa.Column('supabase_auth_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('workers_email_key'), 'workers', type_='unique')
    op.drop_constraint(op.f('workers_phone_key'), 'workers', type_='unique')
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=True)
    op.create_index(op.f('ix_workers_phone'), 'workers', ['phone'], unique=True)
    op.create_index(op.f('ix_workers_supabase_auth_id'), 'workers', ['supabase_auth_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_supabase_auth_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_phone'), table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.create_unique_constraint(op.f('workers_phone_key'), 'workers', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('workers_email_key'), 'workers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('workers', 'supabase_auth_id')
    op.drop_index(op.f('ix_employers_supabase_auth_id'), table_name='employers')
    op.drop_index(op.f('ix_employers_email'), table_name='employers')
    op.create_unique_constraint(op.f('employers_email_key'), 'employers', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('employers', 'supabase_auth_id')
    # ### end Alembic commands ###
