"""add kyc fields to worker

Revision ID: 4e7a1e273515
Revises: 62799541e92f
Create Date: 2026-06-26 13:37:50.289568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4e7a1e273515'
down_revision: Union[str, Sequence[str], None] = '62799541e92f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('workers', sa.Column('kyc_document_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'kyc_document_url')
    op.drop_column('workers', 'is_verified')
    # ### end Alembic commands ###
