"""Add onboarding KYC fields

Revision ID: 6a6a333ac1c0
Revises: 400d7c5d060b
Create Date: 2026-06-28 14:10:17.882990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6a6a333ac1c0'
down_revision: Union[str, Sequence[str], None] = '400d7c5d060b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('business_category', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('annual_revenue', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('description', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('services_required', sa.JSON(), nullable=True))
    op.add_column('employers', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('cin_number', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('director_data', sa.JSON(), nullable=True))
    op.add_column('employers', sa.Column('kyc_aadhaar_number', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('proprietor_name', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('enterprise_phone', sa.String(), nullable=True))
    op.add_column('employers', sa.Column('num_proprietors', sa.Integer(), nullable=True))
    op.add_column('workers', sa.Column('account_type', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('alternate_phone', sa.String(), nullable=True))
    op.add_column('workers', sa.Column('permanent_address', sa.JSON(), nullable=True))
    op.add_column('workers', sa.Column('current_address', sa.JSON(), nullable=True))
    op.add_column('workers', sa.Column('blood_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'blood_group')
    op.drop_column('workers', 'current_address')
    op.drop_column('workers', 'permanent_address')
    op.drop_column('workers', 'alternate_phone')
    op.drop_column('workers', 'account_type')
    op.drop_column('employers', 'num_proprietors')
    op.drop_column('employers', 'enterprise_phone')
    op.drop_column('employers', 'proprietor_name')
    op.drop_column('employers', 'kyc_aadhaar_number')
    op.drop_column('employers', 'director_data')
    op.drop_column('employers', 'cin_number')
    op.drop_column('employers', 'pan_number')
    op.drop_column('employers', 'services_required')
    op.drop_column('employers', 'description')
    op.drop_column('employers', 'annual_revenue')
    op.drop_column('employers', 'website_url')
    op.drop_column('employers', 'business_category')
    op.drop_column('employers', 'account_type')
    # ### end Alembic commands ###
