"""Add udyam number

Revision ID: 881a224a2b77
Revises: 6a6a333ac1c0
Create Date: 2026-06-28 14:29:01.772811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '881a224a2b77'
down_revision: Union[str, Sequence[str], None] = '6a6a333ac1c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('udyam_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employers', 'udyam_number')
    # ### end Alembic commands ###
